export const CREATE_STORY = 'CREATE_STORY'
export const LOAD_STORIES_LIST_SUCCESS = 'LOAD_STORIES_LIST_SUCCESS'
export const LOAD_STORIES_LIST_FAILURE = 'LOAD_STORIES_LIST_FAILURE'
export const FETCHING_STORY_LIST = 'FETCHING_STORY_LIST'
